-- CREATE DATABASE IF NOT EXISTS LeaRecordShop;

-- USE LeaRecordShop;

CREATE TABLE IF NOT EXISTS CLIENTE (
    email VARCHAR(255) NOT NULL,
    nomeCompleto VARCHAR(255) NOT NULL,
    telefone VARCHAR(255) NOT NULL,
    cpf VARCHAR(255) NOT NULL,
    dataNascimento DATE NOT NULL,
    ativo BOOLEAN NOT NULL,
    CONSTRAINT CLIENTE_UK UNIQUE (cpf),
    CONSTRAINT CLIENTE_PK PRIMARY KEY (email)
);

CREATE TABLE IF NOT EXISTS DISCO (
    nomeDisco VARCHAR(255) NOT NULL,
    artista VARCHAR(255) NOT NULL,
    anoLancamento SMALLINT NOT NULL,
    estiloMusical VARCHAR(255) NOT NULL,
    quantidadeDisponivel INTEGER NOT NULL,
    valorUnitario DOUBLE PRECISION NOT NULL,
    CONSTRAINT DISCO_PK PRIMARY KEY (nomeDisco, artista)
);

CREATE TABLE IF NOT EXISTS PEDIDO (
    idPedido SERIAL NOT NULL,
    dataHoraPedido TIMESTAMP NOT NULL,
    valorTotal DOUBLE PRECISION NOT NULL,
    email VARCHAR(255) NOT NULL,
    CONSTRAINT PEDIDO_PK PRIMARY KEY (idPedido),
    CONSTRAINT PEDIDO_CLIENTE_FK FOREIGN KEY (email) REFERENCES CLIENTE (email) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS possui (
    idPedido INTEGER NOT NULL,
    nomeDisco VARCHAR(255) NOT NULL,
    artista VARCHAR(255) NOT NULL,
    quantidade INTEGER NOT NULL,
    CONSTRAINT possui_PEDIDO_FK FOREIGN KEY (idPedido) REFERENCES PEDIDO (idPedido) ON DELETE RESTRICT,
    CONSTRAINT possui_DISCO_FK FOREIGN KEY (nomeDisco, artista) REFERENCES DISCO (nomeDisco, artista) ON DELETE RESTRICT
);